### PR TITLE
Fix for table onselectall event

### PR DESCRIPTION
**Pull request by zdlm**
@wiredearp @zdlm @sampi

Fixes issue #438

### CODE REVIEW

**Comment by wiredearp** [comment]
@zdlm Thanks for digging in. This would correctly implement the functionality as expected in issue https://github.com/Tradeshift/tradeshift-ui/issues/438, this is however not the intended functionality so I have closed the issue. I propose we also discard this PR. The checkbox is not selecting all pages, only the current page, and so it should not fire the callback `onselectall`.

**Comment by zdlm** [comment]
Yes I checked, If I click the menu `all pages` it works fine. But if the table only have one page, It won't trigger `onselectall` event. We can talk about it when you are at office

**Comment by wiredearp** [comment]
Oh.

**Comment by wiredearp** [comment]
And also, of course, the Table cannot know how much “all” is in the database, it can only know the data it has been provided. The purpose of the callback is really to say that the user intends to select one million products in the database and we cannot really convey this intention if we repurpose the callback to fire whenever the local data is selected (the Table doesn’t know if there is more data, only the developer know, that’s why he needs the `onselectall` callback).

**Pull request merged**
