### PR TITLE
ISSUE 227 ts-icon-add icon align in the middle

### PR DESCRIPTION
**Pull request by liufuyang**
@wiredearp @zdlm @sampi

Fixes issue #227

### CODE REVIEW

**Comment by sampi** [comment]
The build is failing because they aren't available to forks =/ https://docs.travis-ci.com/user/environment-variables#Defining-Variables-in-Repository-Settings

**Comment by liufuyang** [comment]
@sampi so should I try make a

**Comment by sampi** [comment]
I'm trying to fix it now

**Comment by sampi** [comment]
Can you rebase on top of master? The Travis-CI build has been fixed with https://github.com/Tradeshift/tradeshift-ui/pull/229

**Comment by sampi** [comment]
Apparently forks won't work, even if I put the encrypted keys in the config file.

**Comment by liufuyang** [comment]
rebased... perhaps we should just forget about the fork pr for now :P

**Pull request merged**
