### PR TITLE
Added code examples to markdown documention

### PR DESCRIPTION
**Pull request by paulswebapps**
@wiredearp @zdlm @sampi

Added code examples to markdown documentation. It could use a little polish, but for now, I fixed the issue with the minimum amount of code changed, so I avoided making changes to the `.xhtml` file.

The only file I changed was `docs/src/xhtml/appendix/markdown/index.js`. The other changes were made by the pre-commit hook.

### CODE REVIEW

**Comment by paulswebapps** [comment]
Amended commit to remove `TODO`  note in the `index.xhtml` file.

**Comment by zdlm** [comment]
👍

**Comment by paulswebapps** [comment]
Amended commit to resolve merge conflict.

**Comment by paulswebapps** [comment]
Crap: not sure why over 100 files are changed now. And the conflict is somehow still not resolved.

**Comment by paulswebapps** [comment]
Okay, I accidentally merged (muscle memory from previous position where we did a lot of merging), and should have rebased. It's all fixed now.

**Comment by sampi** [comment]
See https://github.com/Tradeshift/tradeshift-ui/pull/329 for a mergeable PR.

**Pull request closed without merging**
