### PR TITLE
[Docs] minor updates

### PR DESCRIPTION
**Pull request by wiredearp**
@zdlm @sampi

1. Hide the sticky on some Docs page where it didn't look nice
2. Fix a link that lead to nowhere
3. Document `disabled` buttons in menu and also tweak the CSS (in Runtime)

### CODE REVIEW

**Comment by wiredearp** [comment]
I don't know why the commits from the previous PR shows up in the list for this PR. It's probably because of the `squash and merge` option that I was forced to use cc @sampi

**Comment by sampi** [comment]
@wiredearp can you try to run this? `git pull --rebase origin master` and then `git push origin jmo-sticky --force`

This way you replay your commits on top of master and then forcefully update your branch to be flat. It should make all those extra commits disappear.

**Comment by zdlm** [comment]
Don't worry, You can change whatever you want about the commit messages when you click `Squash and merge`

**Comment by sampi** [comment]
I'll rebase and merge then, before we completely destroy the git history and have changes registered twice and some never.

**Pull request merged**
