### PR TITLE
fix footer collaboration translation of Simplified Chinese

### PR DESCRIPTION
**Pull request by LealLee**
@sampi @zdlm @tynandebold 

Fixes issue 
https://tradeshift.atlassian.net/browse/CPA-13

### CODE REVIEW

**Comment by LealLee** [comment]
@tynandebold The Chinese translation I change in this PR is exactly matching the words `Open collaboration`, there are same meaning. 😄

**Comment by LealLee** [comment]
@zdlm I think "开始聊天" may be not suitable if customer has already start a collaboration,  and "打开对话" is the literal translation of `Open collaboration`.

**Comment by Cherryqsy** [comment]
@LealLee @zdlm Maybe a compromise solution, use"对话“directly or“点此对话”. What do you think?

**Comment by zdlm** [comment]
I created a new PR, because of the failure of travis. 
https://github.com/Tradeshift/tradeshift-ui/pull/724

**Pull request closed without merging**
